import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import "react-toastify/dist/ReactToastify.css"
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import Navbar from '@/components/navbar';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`relative ${inter.className} flex flex-col min-h-screen`}>
        <Navbar />
          <main className='pt-[112px] flex-1'>{children}</main>
        <Footer />
        <ToastContainer
          className={`font-bold`}
          position="bottom-right"
          autoClose={3000}
          theme='colored'
          closeOnClick
          draggable
        />
      </body>
    </html>
  );
}
